POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer 

{
  "title": "Test middleware token",
  "author": "Sean Carroll",
  "url": "https://www.preposterousuniverse.com/podcast/",
  "likes": 7
}